apiVersion: v1
kind: Template
labels:
  template: firefoxkiosk
metadata:
  annotations:
    description: Remote Desktop Kiosk with Firefox
    iconClass: icon-tomcat
    tags: kiosk,firefox,xrdp,vnc
  creationTimestamp: null
  name: firefoxkiosk
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: xrdp-service
  spec:
    ports:
    - port: 3389
      protocol: TCP
      name: centos-xrdp
    selector:
      name: kiosk
- apiVersion: v1
  kind: Service
  metadata:
    name: vnc-service
  spec:
    ports:
    - port: 5901
      protocol: TCP
      name: centos-vnc
    selector:
      name: kiosk
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: centos-xrdp 
  spec:
    tags:
    - name: "latest"
      from:
        Kind: "DockerImage"
        Name: "docker.io/kevensen/centos-xrdp:latest"
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: centos-vnc-firefox
  spec:
    tags:
    - name: "latest"
      from:
        Kind: "DockerImage"
        Name: "docker.io/kevensen/centos-vnc-firefox:latest"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: kiosk
  spec:
    replicas: 1
    selector:
      name: kiosk
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: kiosk
        name: kiosk
      spec:
        containers:
        - name: centos-vnc-firefox
          image: centos-vnc-firefox
          ports:
          - containerPort: 5901
        - name: centos-xrdp
          image: centos-xrdp
          ports:
          - containerPort: 3389
        nodeSelector:
          role: backend
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - centos-xrdp
        from:
          kind: ImageStreamTag
          name: centos-xrdp:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - centos-vnc-firefox
        from:
          kind: ImageStreamTag
          name: centos-vnc-firefox:latest
      type: ImageChange
    - type: ConfigChange
