apiVersion: v1
kind: Template
labels:
  template: Guacamole
metadata:
  annotations:
    description: Guacamole XRDP and VNC over HTML5
    iconClass: icon-tomcat
    tags: guacamole
  creationTimestamp: null
  name: guacamole
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "guacd"
  spec:
    dockerImageRepository: ${GUACD_IMAGE_NAME}

- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "guacamole"
  spec:
    dockerImageRepository: ${GUACAMOLE_IMAGE_NAME}

- apiVersion: v1
  kind: Service
  metadata:
    name: guacd
  spec:
    ports:
    - port: 4822
      protocol: TCP
      targetPort: 4822
    selector:
      name: guacd

- apiVersion: v1
  kind: Service
  metadata:
    name: guacamole
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: guacamole

- apiVersion: v1
  kind: Route
  metadata:
    name: guacamole
  spec:
    to:
      kind: Service
      name: guacamole

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: guacd
  spec:
    replicas: 1
    selector:
      name: guacd
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: guacd
        name: guacd
      spec:
        containers:
        - name: guacd
          image: guacd:latest
          ports:
          - containerPort: 4822
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - guacd
        from:
          kind: ImageStreamTag
          name: guacd:latest
      type: ImageChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: guacamole
  spec:
    replicas: 1
    selector:
      name: guacamole
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: guacamole
        name: guacamole
      spec:
        containers:
        - image: guacamole:latest
          name: guacamole
          ports:
          - containerPort: 8080
          env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_NAME
            value: mysqlhasafirstnameitsoscar
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - guacamole
        from:
          kind: ImageStreamTag
          name: guacamole:latest
      type: ImageChange


parameters:
- description: Guacd Image
  name: GUACD_IMAGE_NAME
  value: docker.io/glyptodon/guacd
  required: true
- description: Guacamole Image
  name: GUACAMOLE_IMAGE_NAME
  value: docker.io/glyptodon/guacamole
  required: true
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET

- description: The username for the MySQL user
  name: MYSQL_USER
  value: guacamole_user
  required: true
- description: The password for the MySQL password
  name: MYSQL_PASSWORD
  value: guacamole_pass
  required: true
- description: The name of the MySQL database
  name: MYSQL_DATABASE
  value: guacamole_db
  required: true
